Repository Octadesk-Tech/chat-bot-builder-client, pull requests merged in 2023-09, with the labels that each got.

#24 fix: some bugs
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/KeyValueInputs.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
  apps/builder/components/shared/TableList.tsx
Labels: review, Extra Small

#25 feat: Improve mock
  apps/builder/.env.local.example
  apps/builder/components/editor/StepsSideBar/StepSideBar.tsx
  apps/builder/contexts/UserContext.tsx
  apps/builder/contexts/WorkspaceContext.tsx
  apps/builder/mocks/environments/mocks/qa.ts
  apps/builder/mocks/environments/qa.ts
  apps/builder/mocks/index.ts
  apps/builder/mocks/octadesk.ts
  apps/builder/next.config.js
  apps/builder/pages/_app.tsx
  apps/builder/pages/typebots.tsx
  apps/builder/pages/typebots/[typebotId]/edit.tsx
  apps/builder/services/octadesk/featureFlags/featureFlags.ts
  yarn.lock
Labels: review, Extra Large

#26 Feat/woz component
  apps/builder/assets/icons.tsx
  apps/builder/components/editor/StepsSideBar/StepIcon.tsx
  apps/builder/components/editor/StepsSideBar/StepSideBar.tsx
  apps/builder/components/editor/StepsSideBar/StepTypeLabel.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/SettingsModal.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/SettingsPopoverContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WOZSuggestion/WOZSuggestionSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/index.ts
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/StepNodeContent/StepNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WOZSuggestion/WOZSuggestionContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WOZSuggestion/index.tsx
  apps/builder/public/images/auto-fix.svg
  apps/builder/services/typebots/typebots.ts
  apps/builder/typebots.ts
  packages/models/src/typebot/steps/bubble.ts
  packages/models/src/typebot/steps/octaStep.ts
  packages/models/src/typebot/steps/steps.ts
  packages/utils/src/utils.ts
  yarn.lock
Labels: review, Medium

#28 Fix/correct features mvp
  README.md
  apps/builder/components/editor/StepsSideBar/StepSideBar.tsx
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppButtonsContent/WhatsAppButtonsNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppOptionsContent/WhatsAppOptionsNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/OfficeHoursBody/DayOfWeek.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/OfficeHoursBody/OfficeHoursBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/OfficeHoursBody/OfficeHoursIntervalTimer.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/OfficeHoursBody/SpecialDate.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/WebhookSettings.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WhatsApp/WhatsAppButtons/WhatsAppButtonsContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/TextBubbleEditor.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/ToolBar.tsx
  apps/builder/components/shared/TableListOcta.tsx
  apps/builder/services/typebots/typebots.ts
  apps/builder/typebots.ts
  apps/builder/util/octaRequest.ts
Labels: Extra Large
