Repository Octadesk-Tech/chat-bot-builder-client, pull requests merged in 2023-07, with the labels that each got.

#11 feat:adjust modal body in webhook component
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/SettingsPopoverContent.tsx
Labels: Extra Small

#10 feat:emoji menu
  apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/ToolBar.tsx
Labels: Small

#13 fix: variable select changes + chat variable bot usage
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/OfficeHoursBody/OfficeHoursBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/Input/InputContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/InputItemsContent/InputItemsContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/OctaCommerceContent/OctaCommerceContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WhatsApp/WhatsAppButtons/WhatsAppButtonsContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WhatsApp/WhatsAppOptions/WhatsAppOptionsContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WithVariableContent.tsx
  apps/builder/components/shared/VariableSearchInput/VariableSearchInput.style.ts
  apps/builder/components/shared/VariableSearchInput/VariableSearchInput.tsx
  apps/builder/contexts/WorkspaceContext.tsx
  packages/models/src/typebot/steps/inputs.ts
  packages/models/src/typebot/steps/octaStep.ts
Labels: review, Small

#14 fix: upload bugs
  apps/builder/assets/OctaDivider.tsx
  apps/builder/assets/icons.tsx
  apps/builder/components/octaComponents/OctaDivider/OctaDivider.tsx
  apps/builder/components/octaComponents/OctaTooltip/OctaTooltip.tsx
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeList/ItemNodesList.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/InputMediaSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/AssignToTeam/AssignToTeamContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/Input/InputContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/InputItemsContent/InputItemsContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/MediaInput/MediaInputContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/OctaCommerceContent/OctaCommerceContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/PreReserve/PreReserveContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WhatsApp/WhatsAppButtons/WhatsAppButtonsContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WhatsApp/WhatsAppOptions/WhatsAppOptionsContent.tsx
  apps/builder/components/shared/ImageUploadContent/ImageUploadContent.tsx
  apps/builder/components/shared/buttons/UploadButton.tsx
  packages/models/src/typebot/steps/bubble.ts
Labels: review, Large

#16 fix: max size error
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/MediaInput/MediaInputContent.tsx
  apps/builder/components/shared/buttons/UploadButton.tsx
Labels: review, Extra Small

#18 Fix/text decorations on content
  apps/builder/assets/icons.tsx
  apps/builder/assets/styles/plate.css
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNode.tsx
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeList/ItemNodesList.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ChoiceInputSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppButtonsListSettings/WhatsAppButtonsListSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppOptionsListSettings/WhatsAppOptionsListSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/AssignToTeam/AssignToTeamContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/Input/InputContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/InputItemsContent/InputItemsContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/MediaInput/MediaInputContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/OctaCommerceContent/OctaCommerceContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/TextHtmlContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WhatsApp/WhatsAppButtons/WhatsAppButtonsContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WhatsApp/WhatsAppOptions/WhatsAppOptionsContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/TextBubbleEditor.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/ToolBar.tsx
  apps/builder/components/shared/VariableSearchInput/VariableSearchInput.tsx
  apps/builder/libs/plate.tsx
Labels: review, Large

#20 fix: edit dialog
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/OfficeHoursNodeContent/OfficeHoursNodeContent.tsx
  apps/builder/contexts/TypebotContext/TypebotContext.tsx
  apps/builder/pages/typebots/[typebotId]/edit.tsx
Labels: Medium

#19 Update README.md
  README.md
Labels: Extra Small

#23 fix: variable over accordion panel for webhook component
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/KeyValueInputs.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/WebhookSettings.tsx
  apps/builder/components/shared/TableList.tsx
Labels: review, Small
