Repository Octadesk-Tech/chat-bot-builder-client, pull requests merged in 2024-03, with the labels that each got.

#54 fix: do not add variable with same token as default
  apps/builder/contexts/WorkspaceContext.tsx
Labels: review, Extra Small

#55 Fix/text option list
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppButtonsContent/WhatsAppButtonsNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppOptionsContent/WhatsAppOptionsNodeContent.tsx
Labels: Extra Small

#56 fix: do not show warning for event flow bot
  apps/builder/components/shared/Graph/Nodes/BlockNode/BlockNode.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
Labels: review, Extra Small

#42 Feat/woz assign
  apps/builder/components/editor/StepsSideBar/StepIcon.tsx
  apps/builder/components/editor/StepsSideBar/StepSideBar.tsx
  apps/builder/components/editor/StepsSideBar/StepTypeLabel.tsx
  apps/builder/components/octaComponents/OctaTooltip/OctaTooltip.tsx
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/ButtonNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppButtonsContent/WhatsAppButtonsNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppOptionsContent/WhatsAppOptionsNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeList/ItemNodesList.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/SettingsPopoverContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WOZAssign/WOZAssignSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/index.ts
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/StepNodeContent/StepNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WOZAssign/WOZAssignContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WOZAssign/index.tsx
  apps/builder/contexts/TypebotContext/actions/items.ts
  apps/builder/services/typebots/typebots.ts
  apps/builder/typebots.ts
  packages/models/src/typebot/steps/bubble.ts
  packages/models/src/typebot/steps/inputs.ts
  packages/models/src/typebot/steps/item.ts
  packages/models/src/typebot/steps/octaStep.ts
  packages/utils/src/utils.ts
Labels: review, Extra Large

#58 Adição botão excluir no item do componente Valide uma informação. E a…
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppButtonsContent/WhatsAppButtonsNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppOptionsContent/WhatsAppOptionsNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConditionSettingsBody/ComparisonsItem.tsx
  apps/builder/components/shared/TableList.tsx
Labels: Small

#60 Fix/botao excluir valide informacao
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConditionSettingsBody/ComparisonsItem.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
Labels: Medium

#62 Subida correão erro iconTrash
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConditionSettingsBody/ComparisonsItem.tsx
Labels: Extra Small

#63 fix: logic for check availability
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/AssignToTeam/AssignToTeamSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/AssignToTeam/AssignToTeamContent.tsx
  packages/models/src/typebot/steps/octaStep.ts
Labels: review, Small

#64 Feat/octa 8005 pending issues list empty fields
  apps/builder/assets/icons.tsx
  apps/builder/components/editor/StepsSideBar/StepIcon.tsx
  apps/builder/components/editor/todoList/index.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/AssignToTeam/AssignToTeamSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ChoiceInputSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/InputSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/OctaCommerceBody/OctaCommerceBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppButtonsListSettings/WhatsAppButtonsListSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppOptionsListSettings/WhatsAppOptionsListSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/TextBubbleEditor.tsx
  apps/builder/components/shared/Graph/Nodes/helpers/helpers.tsx
  apps/builder/contexts/TypebotContext/TypebotContext.tsx
  apps/builder/contexts/TypebotContext/actions/blocks.ts
  apps/builder/contexts/TypebotContext/actions/edges.ts
  apps/builder/contexts/TypebotContext/actions/items.ts
  apps/builder/contexts/TypebotContext/actions/steps.ts
  apps/builder/helpers/block-connections.ts
  apps/builder/libs/theme.ts
  apps/builder/pages/typebots/[typebotId]/edit.tsx
  apps/builder/services/utils/useEmptyFields.ts
  apps/builder/services/utils/useUndo.ts
  package.json
  yarn.lock
Labels: Extra Large

#67 fix: add text type to string comparators
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConditionSettingsBody/ComparisonsItem.tsx
Labels: review, Extra Small
