Repository Octadesk-Tech/chat-bot-builder-client, pull requests merged in 2024-04, with the labels that each got.

#68 fix: show return map on webhook
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/WebhookSettings.tsx
Labels: Extra Small

#70 Feat/octa 8181 anchor
  apps/builder/components/editor/todoList/emptyFieldsItem/index.tsx
  apps/builder/components/editor/todoList/groupsWithoutConectionItem/index.tsx
  apps/builder/components/editor/todoList/index.tsx
  apps/builder/components/shared/Graph/Graph.tsx
  apps/builder/helpers/block-connections.ts
Labels: Medium

#73 feat: it adds validations
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/OfficeHoursBody/OfficeHoursBody.style.ts
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/OfficeHoursBody/OfficeHoursBody.tsx
  package.json
  packages/db/build/tsconfig.tsbuildinfo
  yarn.lock
Labels: Extra Large

#74 Fix/octa 7495 cursor error
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/SettingsPopoverContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/CodeSettings.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/CpfInputSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/DateInputSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/KeyValueInputs.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/VariableForTestInputs.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/WebhookSettings.tsx
  apps/builder/components/shared/Textbox/TextBox.tsx
  apps/builder/components/shared/VariableSearchInput/VariableSearchInput.tsx
Labels: Large

#79 Fix/variable migrated
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/ConditionNodeContent.tsx
  packages/utils/src/utils.ts
Labels: review
