Repository Octadesk-Tech/chat-bot-builder-client, pull requests merged in 2024-02, with the labels that each got.

#39 fix: empty html tags
  apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/TextBubbleEditor.tsx
  apps/builder/pages/typebots.tsx
Labels: review, Extra Small

#38 fix: add max length in bubble editor
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppButtonsContent/WhatsAppButtonsNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppOptionsContent/WhatsAppOptionsNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppButtonsListSettings/WhatsAppButtonsListSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppOptionsListSettings/WhatsAppOptionsListSettingsBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/TextBubbleEditor.tsx
Labels: Medium

#41 Feat/conversation tag
  .gitignore
  .nvmrc
  .vscode/settings.json
  README.md
  apps/builder/assets/icons.tsx
  apps/builder/components/editor/StepsSideBar/StepIcon.tsx
  apps/builder/components/editor/StepsSideBar/StepSideBar.tsx
  apps/builder/components/editor/StepsSideBar/StepTypeLabel.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/SettingsPopoverContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConversationTag/ConversationTagBody.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConversationTag/ConversationTagSelect.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/index.ts
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/StepNodeContent/StepNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/ConversationTag/ConversationTagContent.style.ts
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/ConversationTag/ConversationTagContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/ConversationTag/index.tsx
  apps/builder/contexts/TypebotContext/TypebotContext.tsx
  apps/builder/package.json
  apps/builder/services/octadesk/tags/tags.service.ts
  apps/builder/services/octadesk/tags/tags.types.ts
  apps/builder/services/typebots/typebots.ts
  apps/builder/typebots.ts
  apps/landing-page/package.json
  audit-log.json
  package-lock.json
  package.json
  packages/db/build/tsconfig.tsbuildinfo
  packages/models/src/typebot/steps/octaStep.ts
  packages/models/src/typebot/steps/steps.ts
  yarn.lock
Labels: review, Extra Large

#44 Correção componente whatsapp. Esta correção resolverá a seleção do te…
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppOptionsContent/WhatsAppOptionsNodeContent.tsx
Labels: Extra Small

#47 Subida correção seleção de texto nos botões Whatsapp
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppOptionsContent/WhatsAppOptionsNodeContent.tsx
Labels: Extra Small

#49 Botão excluir nos itens da lista (Valide uma informação)
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConditionSettingsBody/ComparisonsItem.tsx
Labels: Extra Small

#50 Botão excluir nos itens da lista (Valide uma informação) | Posição d…
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConditionSettingsBody/ComparisonsItem.tsx
Labels: Extra Small

#40 Fix/conditional operator v2
  apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/ConditionNodeContent.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConditionSettingsBody/ComparisonsItem.tsx
  apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/Input/InputContent.tsx
  apps/builder/components/shared/VariableSearchInput/VariableSearchInput.tsx
  apps/builder/contexts/WorkspaceContext.tsx
  packages/bot-engine/src/services/logic.ts
  packages/models/src/typebot/steps/logic.ts
Labels: review, Medium
